/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <android/log.h>
/* Header for class com_harish_test_opencvcamera_NativeClass */

using namespace cv;
#ifndef _Included_com_harish_test_opencvcamera_NativeClass
#define _Included_com_harish_test_opencvcamera_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
void detect(Mat& frame);

/*
 * Class:     com_harish_test_opencvcamera_NativeClass
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_harish_test_opencvcamera_NativeClass_faceDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_harish_test_opencvcamera_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_harish_test_opencvcamera_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
